### ISSUE TITLE
midi.lua requires - component, computer, shell 

### ISSUE THREAD

**Issue by tomotello** [OpenPrograms/Sangar-Programs#6]
midi.lua - great code. Where can I get the dependent requires "component", "computer", "shell"
Thanks, Thomas

**Comment by fnuecke** [comment]
To avoid confusion: the midi program (as well as the other programs in this repo) are for the [OpenComputers mod](https://github.com/MightyPirates/OpenComputers). The shell library is part of OpenOS and [can be found here](https://github.com/MightyPirates/OpenComputers/blob/master-MC1.7.10/src/main/resources/assets/opencomputers/loot/OpenOS/lib/shell.lua), the other two are provided 'natively' - their behavior is documented [on the mod's wiki](http://ocdoc.cil.li/) ([`component`](http://ocdoc.cil.li/api:component), [`computer`](http://ocdoc.cil.li/api:computer)).

**Comment by tomotello** [comment]
Thanks a lot! Kind regards, Thomas
